cmake_minimum_required(VERSION 3.22)
set(MONGO_INCLUDE_DIR "/home/subham/cpp_libs/libs_13/mongocxx/include/mongocxx/v_noabi")
set(BSON_INCLUDE_DIR "/home/subham/cpp_libs/libs_13/mongocxx/include/bsoncxx/v_noabi")
set(BSON_THIRD_PARTY_INCLUDE_DIR "/home/subham/cpp_libs/libs_13/mongocxx/include/bsoncxx/v_noabi/bsoncxx/third_party/mnmlstc/")
IF (APPLE)
    set(MONGO_LIB /usr/local/lib/libmongocxx.dylib)
    set(BSON_LIB /usr/local/lib/libbsoncxx.dylib)
ELSE()  # Other platforms
    set(MONGO_LIB /home/subham/cpp_libs/libs_13/mongocxx/lib/libmongocxx.so._noabi)
    set(BSON_LIB /home/subham/cpp_libs/libs_13/mongocxx/lib/libbsoncxx.so._noabi)
ENDIF()
