// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flux_options.proto

#ifndef PROTOBUF_flux_5foptions_2eproto__INCLUDED
#define PROTOBUF_flux_5foptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_flux_5foptions_2eproto();
void protobuf_AssignDesc_flux_5foptions_2eproto();
void protobuf_ShutdownFile_flux_5foptions_2eproto();


// ===================================================================


// ===================================================================

static const int kFluxFileCmntFieldNumber = 51151;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFileCmnt;
static const int kFluxFileModelTypeFieldNumber = 51152;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFileModelType;
static const int kFluxMsgCmntFieldNumber = 51151;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgCmnt;
static const int kFluxMsgRootIdFieldNumber = 51152;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgRootId;
static const int kFluxMsgPrefixPrependFieldNumber = 51153;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgPrefixPrepend;
static const int kFluxMsgTblFieldNumber = 52151;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgTbl;
static const int kFluxMsgTblSharedFieldNumber = 52152;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgTblShared;
static const int kFluxMsgOpNameFieldNumber = 53151;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgOpName;
static const int kFluxMsgRspFieldNumber = 53152;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgRsp;
static const int kFluxMsgNotifyFieldNumber = 53153;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgNotify;
static const int kFluxMsgDaoAccessTypeFieldNumber = 54151;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgDaoAccessType;
static const int kFluxMsgNoExpandFieldNumber = 54152;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgNoExpand;
static const int kFluxMsgOrmRootFieldNumber = 55151;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgOrmRoot;
static const int kFluxMsgOrmCreateUpdateOrDeleteClassesFieldNumber = 55152;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgOrmCreateUpdateOrDeleteClasses;
static const int kFluxMsgOrmReadRespClassesFieldNumber = 55153;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgOrmReadRespClasses;
static const int kFluxMsgCmplxHighFieldNumber = 56151;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgCmplxHigh;
static const int kFluxMsgCmplxMedFieldNumber = 56152;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgCmplxMed;
static const int kFluxMsgCmplxLowFieldNumber = 56153;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxMsgCmplxLow;
static const int kFluxFldCmntFieldNumber = 51151;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldCmnt;
static const int kFluxFldHideFieldNumber = 51152;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldHide;
static const int kFluxFldHelpFieldNumber = 51153;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldHelp;
static const int kFluxFldTblFieldNumber = 52151;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldTbl;
static const int kFluxFldColFieldNumber = 52152;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldCol;
static const int kFluxFldPkFieldNumber = 52153;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldPk;
static const int kFluxFldFkTblFieldNumber = 52154;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldFkTbl;
static const int kFluxFldFkColFieldNumber = 52155;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldFkCol;
static const int kFluxFldCmplxHighFieldNumber = 56151;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldCmplxHigh;
static const int kFluxFldCmplxMedFieldNumber = 56152;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldCmplxMed;
static const int kFluxFldCmplxLowFieldNumber = 56153;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldCmplxLow;
static const int kFluxFldValMinFieldNumber = 59151;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldValMin;
static const int kFluxFldValMaxFieldNumber = 59152;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldValMax;
static const int kFluxFldValListFieldNumber = 59153;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldValList;
static const int kFluxFldTestValFieldNumber = 59154;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldTestVal;
static const int kFluxFldValDateTimeFieldNumber = 59155;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldValDateTime;
static const int kFluxFldMappingSrcTypeFieldNumber = 60151;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  FluxFldMappingSrcType;

// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_flux_5foptions_2eproto__INCLUDED
