// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flux_options.proto

public final class FluxOptions {
  private FluxOptions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(FluxOptions.fluxFileCmnt);
    registry.add(FluxOptions.fluxFileModelType);
    registry.add(FluxOptions.fluxMsgCmnt);
    registry.add(FluxOptions.fluxMsgRootId);
    registry.add(FluxOptions.fluxMsgPrefixPrepend);
    registry.add(FluxOptions.fluxMsgTbl);
    registry.add(FluxOptions.fluxMsgTblShared);
    registry.add(FluxOptions.fluxMsgOpName);
    registry.add(FluxOptions.fluxMsgRsp);
    registry.add(FluxOptions.fluxMsgNotify);
    registry.add(FluxOptions.fluxMsgDaoAccessType);
    registry.add(FluxOptions.fluxMsgNoExpand);
    registry.add(FluxOptions.fluxMsgOrmRoot);
    registry.add(FluxOptions.fluxMsgOrmCreateUpdateOrDeleteClasses);
    registry.add(FluxOptions.fluxMsgOrmReadRespClasses);
    registry.add(FluxOptions.fluxMsgCmplxHigh);
    registry.add(FluxOptions.fluxMsgCmplxMed);
    registry.add(FluxOptions.fluxMsgCmplxLow);
    registry.add(FluxOptions.fluxFldCmnt);
    registry.add(FluxOptions.fluxFldHide);
    registry.add(FluxOptions.fluxFldHelp);
    registry.add(FluxOptions.fluxFldTbl);
    registry.add(FluxOptions.fluxFldCol);
    registry.add(FluxOptions.fluxFldPk);
    registry.add(FluxOptions.fluxFldFkTbl);
    registry.add(FluxOptions.fluxFldFkCol);
    registry.add(FluxOptions.fluxFldCmplxHigh);
    registry.add(FluxOptions.fluxFldCmplxMed);
    registry.add(FluxOptions.fluxFldCmplxLow);
    registry.add(FluxOptions.fluxFldValMin);
    registry.add(FluxOptions.fluxFldValMax);
    registry.add(FluxOptions.fluxFldValList);
    registry.add(FluxOptions.fluxFldTestVal);
    registry.add(FluxOptions.fluxFldValDateTime);
    registry.add(FluxOptions.fluxFldMappingSrcType);
  }
  public static final int FLUXFILECMNT_FIELD_NUMBER = 51151;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.String> fluxFileCmnt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFILEMODELTYPE_FIELD_NUMBER = 51152;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.String> fluxFileModelType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGCMNT_FIELD_NUMBER = 51151;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgCmnt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGROOTID_FIELD_NUMBER = 51152;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgRootId = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGPREFIXPREPEND_FIELD_NUMBER = 51153;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgPrefixPrepend = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGTBL_FIELD_NUMBER = 52151;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgTbl = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGTBLSHARED_FIELD_NUMBER = 52152;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgTblShared = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGOPNAME_FIELD_NUMBER = 53151;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgOpName = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGRSP_FIELD_NUMBER = 53152;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgRsp = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGNOTIFY_FIELD_NUMBER = 53153;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgNotify = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGDAOACCESSTYPE_FIELD_NUMBER = 54151;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgDaoAccessType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGNOEXPAND_FIELD_NUMBER = 54152;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgNoExpand = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGORMROOT_FIELD_NUMBER = 55151;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgOrmRoot = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGORMCREATEUPDATEORDELETECLASSES_FIELD_NUMBER = 55152;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgOrmCreateUpdateOrDeleteClasses = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGORMREADRESPCLASSES_FIELD_NUMBER = 55153;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgOrmReadRespClasses = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGCMPLXHIGH_FIELD_NUMBER = 56151;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgCmplxHigh = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGCMPLXMED_FIELD_NUMBER = 56152;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgCmplxMed = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXMSGCMPLXLOW_FIELD_NUMBER = 56153;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> fluxMsgCmplxLow = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDCMNT_FIELD_NUMBER = 51151;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldCmnt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDHIDE_FIELD_NUMBER = 51152;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldHide = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDHELP_FIELD_NUMBER = 51153;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldHelp = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDTBL_FIELD_NUMBER = 52151;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldTbl = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDCOL_FIELD_NUMBER = 52152;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldCol = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDPK_FIELD_NUMBER = 52153;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldPk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDFKTBL_FIELD_NUMBER = 52154;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldFkTbl = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDFKCOL_FIELD_NUMBER = 52155;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldFkCol = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDCMPLXHIGH_FIELD_NUMBER = 56151;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldCmplxHigh = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDCMPLXMED_FIELD_NUMBER = 56152;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldCmplxMed = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDCMPLXLOW_FIELD_NUMBER = 56153;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldCmplxLow = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDVALMIN_FIELD_NUMBER = 59151;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldValMin = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDVALMAX_FIELD_NUMBER = 59152;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldValMax = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDVALLIST_FIELD_NUMBER = 59153;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldValList = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDTESTVAL_FIELD_NUMBER = 59154;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldTestVal = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDVALDATETIME_FIELD_NUMBER = 59155;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldValDateTime = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int FLUXFLDMAPPINGSRCTYPE_FIELD_NUMBER = 60151;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> fluxFldMappingSrcType = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022flux_options.proto\032 google/protobuf/de" +
      "scriptor.proto:4\n\014FluxFileCmnt\022\034.google." +
      "protobuf.FileOptions\030\317\217\003 \001(\t:9\n\021FluxFile" +
      "ModelType\022\034.google.protobuf.FileOptions\030" +
      "\320\217\003 \001(\t:6\n\013FluxMsgCmnt\022\037.google.protobuf" +
      ".MessageOptions\030\317\217\003 \001(\t:8\n\rFluxMsgRootId" +
      "\022\037.google.protobuf.MessageOptions\030\320\217\003 \001(" +
      "\t:?\n\024FluxMsgPrefixPrepend\022\037.google.proto" +
      "buf.MessageOptions\030\321\217\003 \001(\t:5\n\nFluxMsgTbl" +
      "\022\037.google.protobuf.MessageOptions\030\267\227\003 \001(",
      "\t:;\n\020FluxMsgTblShared\022\037.google.protobuf." +
      "MessageOptions\030\270\227\003 \001(\t:8\n\rFluxMsgOpName\022" +
      "\037.google.protobuf.MessageOptions\030\237\237\003 \001(\t" +
      ":5\n\nFluxMsgRsp\022\037.google.protobuf.Message" +
      "Options\030\240\237\003 \001(\t:8\n\rFluxMsgNotify\022\037.googl" +
      "e.protobuf.MessageOptions\030\241\237\003 \001(\t:?\n\024Flu" +
      "xMsgDaoAccessType\022\037.google.protobuf.Mess" +
      "ageOptions\030\207\247\003 \001(\t::\n\017FluxMsgNoExpand\022\037." +
      "google.protobuf.MessageOptions\030\210\247\003 \001(\t:9" +
      "\n\016FluxMsgOrmRoot\022\037.google.protobuf.Messa",
      "geOptions\030\357\256\003 \001(\t:P\n%FluxMsgOrmCreateUpd" +
      "ateOrDeleteClasses\022\037.google.protobuf.Mes" +
      "sageOptions\030\360\256\003 \001(\t:D\n\031FluxMsgOrmReadRes" +
      "pClasses\022\037.google.protobuf.MessageOption" +
      "s\030\361\256\003 \001(\t:;\n\020FluxMsgCmplxHigh\022\037.google.p" +
      "rotobuf.MessageOptions\030\327\266\003 \001(\t::\n\017FluxMs" +
      "gCmplxMed\022\037.google.protobuf.MessageOptio" +
      "ns\030\330\266\003 \001(\t::\n\017FluxMsgCmplxLow\022\037.google.p" +
      "rotobuf.MessageOptions\030\331\266\003 \001(\t:4\n\013FluxFl" +
      "dCmnt\022\035.google.protobuf.FieldOptions\030\317\217\003",
      " \001(\t:4\n\013FluxFldHide\022\035.google.protobuf.Fi" +
      "eldOptions\030\320\217\003 \001(\t:4\n\013FluxFldHelp\022\035.goog" +
      "le.protobuf.FieldOptions\030\321\217\003 \001(\t:3\n\nFlux" +
      "FldTbl\022\035.google.protobuf.FieldOptions\030\267\227" +
      "\003 \001(\t:3\n\nFluxFldCol\022\035.google.protobuf.Fi" +
      "eldOptions\030\270\227\003 \001(\t:2\n\tFluxFldPk\022\035.google" +
      ".protobuf.FieldOptions\030\271\227\003 \001(\t:5\n\014FluxFl" +
      "dFkTbl\022\035.google.protobuf.FieldOptions\030\272\227" +
      "\003 \001(\t:5\n\014FluxFldFkCol\022\035.google.protobuf." +
      "FieldOptions\030\273\227\003 \001(\t:9\n\020FluxFldCmplxHigh",
      "\022\035.google.protobuf.FieldOptions\030\327\266\003 \001(\t:" +
      "8\n\017FluxFldCmplxMed\022\035.google.protobuf.Fie" +
      "ldOptions\030\330\266\003 \001(\t:8\n\017FluxFldCmplxLow\022\035.g" +
      "oogle.protobuf.FieldOptions\030\331\266\003 \001(\t:6\n\rF" +
      "luxFldValMin\022\035.google.protobuf.FieldOpti" +
      "ons\030\217\316\003 \001(\t:6\n\rFluxFldValMax\022\035.google.pr" +
      "otobuf.FieldOptions\030\220\316\003 \001(\t:7\n\016FluxFldVa" +
      "lList\022\035.google.protobuf.FieldOptions\030\221\316\003" +
      " \001(\t:7\n\016FluxFldTestVal\022\035.google.protobuf" +
      ".FieldOptions\030\222\316\003 \001(\t:;\n\022FluxFldValDateT",
      "ime\022\035.google.protobuf.FieldOptions\030\223\316\003 \001" +
      "(\t:>\n\025FluxFldMappingSrcType\022\035.google.pro" +
      "tobuf.FieldOptions\030\367\325\003 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          fluxFileCmnt.internalInit(descriptor.getExtensions().get(0));
          fluxFileModelType.internalInit(descriptor.getExtensions().get(1));
          fluxMsgCmnt.internalInit(descriptor.getExtensions().get(2));
          fluxMsgRootId.internalInit(descriptor.getExtensions().get(3));
          fluxMsgPrefixPrepend.internalInit(descriptor.getExtensions().get(4));
          fluxMsgTbl.internalInit(descriptor.getExtensions().get(5));
          fluxMsgTblShared.internalInit(descriptor.getExtensions().get(6));
          fluxMsgOpName.internalInit(descriptor.getExtensions().get(7));
          fluxMsgRsp.internalInit(descriptor.getExtensions().get(8));
          fluxMsgNotify.internalInit(descriptor.getExtensions().get(9));
          fluxMsgDaoAccessType.internalInit(descriptor.getExtensions().get(10));
          fluxMsgNoExpand.internalInit(descriptor.getExtensions().get(11));
          fluxMsgOrmRoot.internalInit(descriptor.getExtensions().get(12));
          fluxMsgOrmCreateUpdateOrDeleteClasses.internalInit(descriptor.getExtensions().get(13));
          fluxMsgOrmReadRespClasses.internalInit(descriptor.getExtensions().get(14));
          fluxMsgCmplxHigh.internalInit(descriptor.getExtensions().get(15));
          fluxMsgCmplxMed.internalInit(descriptor.getExtensions().get(16));
          fluxMsgCmplxLow.internalInit(descriptor.getExtensions().get(17));
          fluxFldCmnt.internalInit(descriptor.getExtensions().get(18));
          fluxFldHide.internalInit(descriptor.getExtensions().get(19));
          fluxFldHelp.internalInit(descriptor.getExtensions().get(20));
          fluxFldTbl.internalInit(descriptor.getExtensions().get(21));
          fluxFldCol.internalInit(descriptor.getExtensions().get(22));
          fluxFldPk.internalInit(descriptor.getExtensions().get(23));
          fluxFldFkTbl.internalInit(descriptor.getExtensions().get(24));
          fluxFldFkCol.internalInit(descriptor.getExtensions().get(25));
          fluxFldCmplxHigh.internalInit(descriptor.getExtensions().get(26));
          fluxFldCmplxMed.internalInit(descriptor.getExtensions().get(27));
          fluxFldCmplxLow.internalInit(descriptor.getExtensions().get(28));
          fluxFldValMin.internalInit(descriptor.getExtensions().get(29));
          fluxFldValMax.internalInit(descriptor.getExtensions().get(30));
          fluxFldValList.internalInit(descriptor.getExtensions().get(31));
          fluxFldTestVal.internalInit(descriptor.getExtensions().get(32));
          fluxFldValDateTime.internalInit(descriptor.getExtensions().get(33));
          fluxFldMappingSrcType.internalInit(descriptor.getExtensions().get(34));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
