# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ui_core.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rui_core.proto\"E\n\x0cWidgetUIData\x12\t\n\x01i\x18\x01 \x02(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\t\n\x01w\x18\x04 \x01(\x05\x12\t\n\x01h\x18\x05 \x01(\x05*3\n\x05Theme\x12\x15\n\x11THEME_UNSPECIFIED\x10\x00\x12\x08\n\x04\x44\x41RK\x10\x01\x12\t\n\x05LIGHT\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ui_core_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _THEME._serialized_start=88
  _THEME._serialized_end=139
  _WIDGETUIDATA._serialized_start=17
  _WIDGETUIDATA._serialized_end=86
# @@protoc_insertion_point(module_scope)
