# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ui_core.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rui_core.proto\"E\n\x0cWidgetUIData\x12\t\n\x01i\x18\x01 \x02(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\t\n\x01w\x18\x04 \x01(\x05\x12\t\n\x01h\x18\x05 \x01(\x05\"\xca\x01\n\x08UIButton\x12\x19\n\x11unpressed_caption\x18\x01 \x01(\t\x12\x17\n\x0fpressed_caption\x18\x02 \x01(\t\x12 \n\x0b\x62utton_type\x18\x03 \x01(\x0e\x32\x0b.ButtonType\x12 \n\x0b\x62utton_size\x18\x04 \x01(\x0e\x32\x0b.ButtonSize\x12\x17\n\x0fvalue_color_map\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x06 \x01(\t\x12\x1d\n\x15pressed_value_as_text\x18\x07 \x02(\t*[\n\nButtonType\x12\x1b\n\x17\x42UTTON_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x42UTTON_TYPE_ROUND\x10\x01\x12\x19\n\x15\x42UTTON_TYPE_RECTANGLE\x10\x02*o\n\nButtonSize\x12\x1b\n\x17\x42UTTON_SIZE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x42UTTON_SIZE_SMALL\x10\x01\x12\x16\n\x12\x42UTTON_SIZE_MEDIUM\x10\x02\x12\x15\n\x11\x42UTTON_SIZE_LARGE\x10\x03*?\n\x05Theme\x12\x15\n\x11THEME_UNSPECIFIED\x10\x00\x12\x0e\n\nTHEME_DARK\x10\x01\x12\x0f\n\x0bTHEME_LIGHT\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ui_core_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUTTONTYPE._serialized_start=293
  _BUTTONTYPE._serialized_end=384
  _BUTTONSIZE._serialized_start=386
  _BUTTONSIZE._serialized_end=497
  _THEME._serialized_start=499
  _THEME._serialized_end=562
  _WIDGETUIDATA._serialized_start=17
  _WIDGETUIDATA._serialized_end=86
  _UIBUTTON._serialized_start=89
  _UIBUTTON._serialized_end=291
# @@protoc_insertion_point(module_scope)
