syntax = "proto2";

import "ui_option_utils.proto";
import "flux_options.proto";
import "projects_core.proto";
import "base_log_book_core.proto";

package phone_log_book;

option (FluxFileDateTimeGranularity) = MILLI_SEC;
option (FluxFileDateTimePrintTimezone) = "LOCAL";

message PlanAlert {
  option (FluxMsgJsonRoot) = {
    CreateOp: AggregateType_UNSPECIFIED,
    CreateAllOp: AggregateType_UNSPECIFIED
    ReadOp: AggregateType_FilterAggregate,
    ReadAllOp: AggregateType_FilterAggregate,
    UpdateOp: AggregateType_UNSPECIFIED,
    UpdateAllOp: AggregateType_UNSPECIFIED,
    PatchOp: AggregateType_UNSPECIFIED,
    PatchAllOp: AggregateType_UNSPECIFIED,
    DeleteOp: AggregateType_UNSPECIFIED,
    DeleteAllOp: AggregateType_UNSPECIFIED,
    DeleteByIdListOp: AggregateType_UNSPECIFIED,
    ReadByIDWebSocketOp: AggregateType_UNSPECIFIED
  };
  option (FluxMsgWidgetUIDataElement) = {
    x: 0,
    y: 32,
    w: 8,
    h: 8,
    is_repeated: true,
    widget_ui_data: {
      view_layout: UI_TABLE
    },
    is_read_only: true,
    is_model_alert_type: true
  };
  option (FluxMsgServerSideFilterSort) = true;
  option (FluxMsgDefaultFilterParam) = {
      param_src_model_name: "PairPlan",
      ui_filter_params: {
          param_name: "plan_id",
          param_value_src: "PairPlan.id"
      },
      ui_filter_params: {
          param_name: "dismiss",
          param_value: "false"
      }
  };
  option (FluxMsgButtonQuery) = {       // implement
    query_data: {
      QueryName: "dismiss_all_plan_alert_by_plan_id"
      QueryType: HTTP
      QueryParams: {
        QueryParamName: "plan_id",
        QueryParamDataType: "int"
      }
    };
    ui_button: {
      unpressed_caption: "DISMISS ALL",
      pressed_caption: "DISMISS ALL IN PROGRESS",
      color: "true=DEBUG,false=INFO",
      button_type: BUTTON_TYPE_RECTANGLE,
      button_size: BUTTON_SIZE_MEDIUM,
      action: "flux_toggle",
      pressed_value_as_text: "true"
    }
  };
  option (FluxMsgJsonQuery) = {
      QueryName: "create_or_update_plan_alert"
      QueryParams: {
        QueryParamName: "plan_id",
        QueryParamDataType: "int"
      }
      QueryParams: {
        QueryParamName: "severity",
        QueryParamDataType: "str"
      }
      QueryParams: {
        QueryParamName: "alert_brief",
        QueryParamDataType: "str"
      }
      QueryParams: {
        QueryParamName: "alert_details",
        QueryParamDataType: "str | None = None"
      }
  };
  option (FluxMsgStringLength) = 128;

  option (FluxMsgUIGetAllLimit) = "100";
  option (FluxMsgMainCRUDOperationsAgg) = {
    agg_var_name: "sort_alerts_based_on_severity_n_last_update_analyzer_time",
    override_get_all_limit_handling: true
  };
  required int32 id = 1 [(FluxFldOrmNoUpdate) = true, (FluxFldServerPopulate) = true, (FluxFldHide) = "True"];
  required int32 plan_id = 2 [(FluxFldQueryParamBind) = "plan_id", (FluxFldServerPopulate) = true, (FluxFldHide) = "True", (FluxFldIndex) = true, (FluxFldOrmNoUpdate) = true];
  optional bool dismiss = 3 [default=false, (FluxFldIndex) = true, (FluxFldUIUpdateOnly) = true, (FluxFldSequenceNumber) = 1, (FluxFldNoCommonKey) = true, (FluxFldButton) = {
    unpressed_caption: "dismiss",
    pressed_caption: "undo",
    color: "true=DEBUG,false=INFO"
    button_type: BUTTON_TYPE_RECTANGLE,
    button_size: BUTTON_SIZE_MEDIUM,
    action: "flux_toggle",
    pressed_value_as_text: "true",
    allow_force_update: true
  }];
  required Severity severity = 4 [(FluxFldColor) = "Severity_CRITICAL=CRITICAL,Severity_ERROR=ERROR,Severity_WARNING=WARNING,Severity_INFO=INFO, Severity_DEBUG=DEBUG, Severity_UNSPECIFIED=UNSPECIFIED", (FluxFldOrmNoUpdate) = true];
  optional int32 alert_count = 5 [(FluxFldOrmNoUpdate) = true, (FluxFldColumnSize) = "small"];
  required string alert_brief = 6 [(FluxFldSizeMax) = 32, (FluxFldTextAlign) = "left", (FluxFldOrmNoUpdate) = true];
  // must prefix plan:<plan-name> for plan alerts
  optional AlertMeta alert_meta = 7 [(FluxFldAbbreviated) = "JSON", (FluxFldOrmNoUpdate) = true];
  optional int64 last_update_analyzer_time = 8 [(FluxFldValIsDateTime) = true, (FluxFldOrmNoUpdate) = true];
}

message DismissPlanAlertByBriefStr {
  option (FluxMsgJsonQuery) = {
    QueryName: "dismiss_plan_alert_by_brief_str"
    QueryParams: {
      QueryParamName: "plan_id",
      QueryParamDataType: "int"
    },
    QueryParams: {
      QueryParamName: "brief_str",
      QueryParamDataType: "str"
    },
    QueryRouteType: PATCH
  };
  optional bool temp = 1;
}

message ShutDownLogAnalyzer {
  option (FluxMsgJsonQuery) = {
      QueryName: "shutdown_phone_log_book"
  };
  optional bool temp = 1;
}

message PlanAlertCacheDictByPlanIdDict {
  option (FluxMsgJsonQuery) = {
    QueryName: "verify_plan_alert_id_in_plan_alert_cache_dict_by_plan_id_dict"
    QueryParams: {
      QueryParamName: "plan_id",
      QueryParamDataType: "int"
    },
    QueryParams: {
      QueryParamName: "plan_cache_key",
      QueryParamDataType: "str"
    },
    QueryRouteType: PATCH
  };
  optional bool is_key_present = 1;
}

message PlanStateUpdateMatcherForSymbolSideLog {
  option (FluxMsgJsonQuery) = {
    QueryName: "plan_state_update_matcher_for_symbol_side_log"
    QueryRouteType: POST_ALL,
    QueryParams: {
      QueryParamName: "payload",
      QueryParamDataType: "List[Dict]"
    }
  };
  optional bool temp = 1;  // no use case - kept as st least 1 field must be present in message
}

message PlanStateUpdateMatcherForPlanIdLog {
  option (FluxMsgJsonQuery) = {
    QueryName: "plan_state_update_matcher_for_plan_id_log"
    QueryRouteType: POST_ALL,
    QueryParams: {
      QueryParamName: "payload",
      QueryParamDataType: "List[Dict]"
    }
  };
  optional bool temp = 1;  // no use case - kept as st least 1 field must be present in message
}

message EnableDisablePlanAlertCreate {
  option (FluxMsgJsonQuery) = {
    QueryName: "enable_disable_plan_alert_create"
    QueryRouteType: POST_ALL,
    QueryParams: {
      QueryParamName: "payload",
      QueryParamDataType: "List[Dict]"
    }
  };
  optional bool is_id_present = 1;  // no use case - kept as st least 1 field must be present in message
}


message HandleSimulateLog {
  option (FluxMsgJsonQuery) = {
    QueryName: "handle_simulate_log"
    QueryParams: {
      QueryParamName: "payload",
      QueryParamDataType: "List[Dict]"
    },
    QueryRouteType: POST_ALL,
  };
  optional bool is_id_present = 1;  // no use case - kept as st least 1 field must be present in message
}


message HandlePlanAlertsWithPlanId{
  option (FluxMsgJsonQuery) = {
    QueryName: "handle_plan_alerts_with_plan_id"
    QueryRouteType: POST_ALL,
    QueryParams: {
      QueryParamName: "payload",
      QueryParamDataType: "List[Dict]"
    }
  };
  optional bool is_id_present = 1;  // no use case - kept as st least 1 field must be present in message
}

message HandlePlanAlertsWithSymbolSide{
  option (FluxMsgJsonQuery) = {
    QueryName: "handle_plan_alerts_with_symbol_side"
    QueryRouteType: POST_ALL,
    QueryParams: {
      QueryParamName: "payload",
      QueryParamDataType: "List[Dict]"
    }
  };
  optional bool is_id_present = 1;  // no use case - kept as st least 1 field must be present in message
}

message HandlePairPlanUpdatesFromLogs{
    option (FluxMsgJsonQuery) = {
    QueryName: "handle_pair_plan_updates_from_logs"
    QueryRouteType: POST_ALL,
    QueryParams: {
      QueryParamName: "payload",
      QueryParamDataType: "List[Dict]"
    }
  };
  optional bool temp = 1;
}

message HandlePosDisableFromPlanIdLog{
  option (FluxMsgJsonQuery) = {
    QueryName: "handle_pos_disable_from_plan_id_log"
    QueryRouteType: POST_ALL,
    QueryParams: {
      QueryParamName: "payload",
      QueryParamDataType: "List[Dict]"
    }
  };
  optional bool is_id_present = 1;  // no use case - kept as st least 1 field must be present in message
}

message HandlePosDisableFromSymbolSideLog{
  option (FluxMsgJsonQuery) = {
    QueryName: "handle_pos_disable_from_symbol_side_log"
    QueryRouteType: POST_ALL,
    QueryParams: {
      QueryParamName: "payload",
      QueryParamDataType: "List[Dict]"
    }
  };
  optional bool is_id_present = 1;  // no use case - kept as st least 1 field must be present in message
}

message HandlePlanPauseFromPlanIdLog{
  option (FluxMsgJsonQuery) = {
    QueryName: "handle_plan_pause_from_plan_id_log"
    QueryRouteType: POST_ALL,
    QueryParams: {
      QueryParamName: "payload",
      QueryParamDataType: "List[Dict]"
    }
  };
  optional bool is_id_present = 1;  // no use case - kept as at least 1 field must be present in message
}

message HandlePlanPauseFromSymbolSideLog{
  option (FluxMsgJsonQuery) = {
    QueryName: "handle_plan_pause_from_symbol_side_log"
    QueryRouteType: POST_ALL,
    QueryParams: {
      QueryParamName: "payload",
      QueryParamDataType: "List[Dict]"
    }
  };
  optional bool is_id_present = 1;  // no use case - kept as at least 1 field must be present in message
}

message HandleContactAlerts{
  option (FluxMsgJsonQuery) = {
    QueryName: "handle_contact_alerts"
    QueryRouteType: POST_ALL,
    QueryParams: {
      QueryParamName: "payload",
      QueryParamDataType: "List[Dict]"
    }
  };
  optional bool is_id_present = 1;  // no use case - kept as st least 1 field must be present in message
}


// used to avoid unused import warning by using any random msg or enum from imported file causing warning
message ImportWarningAvoidDummyMessage {
  optional ButtonType temp = 1;
}
