# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ui_core.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import flux_options_pb2 as flux__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ui_core.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rui_core.proto\x1a\x12\x66lux_options.proto\"E\n\x0cWidgetUIData\x12\t\n\x01i\x18\x01 \x02(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\t\n\x01w\x18\x04 \x01(\x05\x12\t\n\x01h\x18\x05 \x01(\x05*3\n\x05Theme\x12\x15\n\x11THEME_UNSPECIFIED\x10\x00\x12\x08\n\x04\x44\x41RK\x10\x01\x12\t\n\x05LIGHT\x10\x03'
  ,
  dependencies=[flux__options__pb2.DESCRIPTOR,])

_THEME = _descriptor.EnumDescriptor(
  name='Theme',
  full_name='Theme',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='THEME_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DARK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LIGHT', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=108,
  serialized_end=159,
)
_sym_db.RegisterEnumDescriptor(_THEME)

Theme = enum_type_wrapper.EnumTypeWrapper(_THEME)
THEME_UNSPECIFIED = 0
DARK = 1
LIGHT = 3



_WIDGETUIDATA = _descriptor.Descriptor(
  name='WidgetUIData',
  full_name='WidgetUIData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='i', full_name='WidgetUIData.i', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='WidgetUIData.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='WidgetUIData.y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='w', full_name='WidgetUIData.w', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='h', full_name='WidgetUIData.h', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['WidgetUIData'] = _WIDGETUIDATA
DESCRIPTOR.enum_types_by_name['Theme'] = _THEME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WidgetUIData = _reflection.GeneratedProtocolMessageType('WidgetUIData', (_message.Message,), {
  'DESCRIPTOR' : _WIDGETUIDATA,
  '__module__' : 'ui_core_pb2'
  # @@protoc_insertion_point(class_scope:WidgetUIData)
  })
_sym_db.RegisterMessage(WidgetUIData)


# @@protoc_insertion_point(module_scope)
